### ISSUE TITLE
Ignoreremo la criptografia delle comunicazioni client-server.

### ISSUE THREAD

**Issue by lorenzotinfena** [SnoozeHub/.github#5]
Ignoreremo la criptografia delle comunicazioni client-server, dato che al fine del progetto, il sito non verrà pubblicato

**Comment by Seba-T** [comment]
Non bene

**Comment by Seba-T** [comment]
come abbiamo concluso confrontandoci, la crittografia delle comunicazioni client-server sarà parte integrante del progetto (vedi RNF6).
